
-- SCRIPT STARTS --

-- CREATE SCRIPT FOR GCD_MASTER TO HOLD GCD INPUTS AND PROCESSED RECORDS --
 
 CREATE TABLE GCD_MASTER(REF_NO VARCHAR2(20), NO_1 NUMBER(21,7), NO_2 NUMBER(21,7), CALC_GCD NUMBER(21,7), PROCESS_FLG VARCHAR2(1));

 -- CREATE SEQUENCE FOR REF_NO [GCD_MASTER] --

 CREATE SEQUENCE REFNO_SEQ
 START WITH 10
 INCREMENT BY 1
 NOCYCLE
 NOCACHE;

 -- SCRIPT ENDS --